config/routes.rb
Rails.application.routes.draw do
  resources :workshops
  resources :about_us
  resources :courses
  resources :homes
  root to: 'welcome#index'

  devise_scope :user do
  	get "/sign_up" => "devise/registrations#new", :as => "iglawebregistro" #custom path
  end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/workshop.rb
class Workshop < ApplicationRecord
	has_attached_file :avatar, styles: { medium: "300x300", thumb:"100x100"}, default_url: "missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController
  before_action :set_workshop, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /workshops
  # GET /workshops.json
  def index
    @workshops = Workshop.all
  end

  # GET /workshops/1
  # GET /workshops/1.json
  def show
  end

  # GET /workshops/new
  def new
    @workshop = Workshop.new
  end

  # GET /workshops/1/edit
  def edit
  end

  # POST /workshops
  # POST /workshops.json
  def create
    @workshop = Workshop.new(workshop_params)

    respond_to do |format|
      if @workshop.save
        format.html { redirect_to @workshop, notice: 'Workshop was successfully created.' }
        format.json { render :show, status: :created, location: @workshop }
      else
        format.html { render :new }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workshops/1
  # PATCH/PUT /workshops/1.json
  def update
    respond_to do |format|
      if @workshop.update(workshop_params)
        format.html { redirect_to @workshop, notice: 'Workshop was successfully updated.' }
        format.json { render :show, status: :ok, location: @workshop }
      else
        format.html { render :edit }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workshops/1
  # DELETE /workshops/1.json
  def destroy
    @workshop.destroy
    respond_to do |format|
      format.html { redirect_to workshops_url, notice: 'Workshop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workshop
      @workshop = Workshop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workshop_params
      params.require(:workshop).permit(:first_title, :first_description, :avatar)
    end
end

app/helpers/workshops_helper.rb
module WorkshopsHelper
end

app/views/workshops/_form.html.erb
<%= form_with(model: workshop, local: true) do |form| %>
  <% if workshop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(workshop.errors.count, "error") %> prohibited this workshop from being saved:</h2>

      <ul>
      <% workshop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Nombre_Taller %>
    <%= form.text_field :first_title, id: :workshop_first_title, :class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :Descripcion_Taller %>
    <%= form.text_area :first_description, id: :workshop_first_description, :class => "form-control" %>
  </div>

   <div class="field">
        <%= form.label :"imagen1" %><br />
        <%= form.file_field :avatar %>
    </div>

  <div class="actions">
    <%= form.submit :type => "submit", :class => "btn btn-default" %>
  </div>
<% end %>

app/views/workshops/_workshop1.html.erb
<section class="post-list" id="news">
		<div class="container overflow-hidden">
			<div class="row">
				<div class="col-md-12">
					<h3 class="section-heading">Novedades</h3>
				</div>

				<div class="post-slider col-md-12">
					<!-- NEWS CAROSUEL -->
					<div class="swiper-wrapper">
						<!-- SINGLE NEWS ITEM -->
						<% @workshops.each do |workshop| %>
						<div class="swiper-slide">
							<div class="post-entry wow fadeInUp">
								<a href="/workshops/<%=workshop.id%>" data-toggle="modal" data-target="">
									<span class="post-entry-cover" style="background-image:url(<%=workshop.avatar.url()%>);">
									</span>
								</a>

								<a class="h3" href="/workshops/<%=workshop.id%>" data-toggle="modal" data-target="">
									<%=workshop.first_title%>
								</a>
								<a href="#" data-toggle="modal" data-target="#post-01" class="post-entry-more">
									leer mas 
									<span class="ti-arrow-right icon"></span>
								</a>
							</div>
						</div>
						<%end%>
						<!-- / SINGLE NEWS ITEM -->
						
					</div>
					<!-- / NEWS CAROSUEL -->

					<!-- CAROUSEL CONTROLS -->
					<div class="post-pagination text-center"></div>
					<div class="post-slider-next right-arrow-negative"> 
						<span class="ti-arrow-right"></span>
					</div>
					
					<div class="post-slider-prev left-arrow-negative"> 
						<span class="ti-arrow-left"></span>
					</div>
					<!-- / CAROUSEL CONTROLS -->
				</div>
			</div>

					
		</div>
	</section>

app/views/workshops/edit.html.erb
<h1>Editing Workshop</h1>

<%= render 'form', workshop: @workshop %>

<%= link_to 'Show', @workshop %> |
<%= link_to 'Back', workshops_path %>

app/views/workshops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Workshops</h1>

<table>
  <thead>
    <tr>
      <th>First title</th>
      <th>First description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workshops.each do |workshop| %>
      <tr>
        <td><%= workshop.first_title %></td>
        <td><%= workshop.first_description %></td>
        <td><%= link_to 'Show', workshop %></td>
        <td><%= link_to 'Edit', edit_workshop_path(workshop) %></td>
        <td><%= link_to 'Destroy', workshop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Workshop', new_workshop_path %>

app/views/workshops/new.html.erb
<div class="col-md-8 col-md-push-1">
<h1 class="section-heading white-color">Nueva Novedad</h1>

<%= render 'form', workshop: @workshop %>

<%= link_to 'Back', workshops_path %>

app/views/workshops/show.html.erb
	<!-- MODAL CONTENT -->
          <div class="container">
            <a class="close" data-dismiss="modal"> <span class="ti-close"></span></a>
            <div class="modal-body">
              <!-- Wrapper for slides -->
              <div class="carousel slide product-slide" id="product-carousel">
                <!-- CAROSUEL SLIDER -->
                <div class="carousel-inner cont-slider">
                  <div class="item active"> <img alt="" src="<%=@workshop.avatar.url()%>" title=""> </div>
                  
                </div>
                <!-- / CAROSUEL SLIDER -->

                <!-- CAROUSEL INDICATORS -->
                <ol class="carousel-indicators">
                  <li class="active" data-slide-to="0" data-target="#product-carousel"> 
                    <img alt="" src="<%=@workshop.avatar.url()%>"> 
                  </li>

                
                </ol>
                <!-- / CAROUSEL INDICATORS -->
              </div>

              <!-- PRODUCT DESCRIPTION -->
              <div class="container">
                

                <div class="row">
                  <div class="col-md-8 col-md-push-2 product-description">
                    <h4 class="section-heading"><%=@workshop.first_title%></h4>
                    <p> <%=@workshop.first_description%> </p>

                    

                    

                   
                  </div>
                </div>
              </div>
              <!-- / PRODUCT DESCRIPTION -->
            </div>
          </div>
          
          <!-- / MODAL CONTENT -->


<%= link_to 'Edit', edit_workshop_path(@workshop) %> |
<%= link_to 'Back', workshops_path %>