config/routes.rb
Rails.application.routes.draw do
  resources :workshops
  resources :about_us
  resources :courses
  resources :homes
  root to: 'welcome#index'

  devise_scope :user do
  	get "/sign_up" => "devise/registrations#new", :as => "iglawebregistro" #custom path
  end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/about_u.rb
class AboutU < ApplicationRecord
	has_attached_file :avatar, styles: { medium: "300x300", thumb:"100x100"}, default_url: "missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
    has_attached_file :avatar1, styles: { medium: "300x300", thumb:"100x100"}, default_url: "missing.png"
    validates_attachment_content_type :avatar1, content_type: /\Aimage\/.*\Z/
    has_attached_file :avatar2, styles: { medium: "300x300", thumb:"100x100"}, default_url: "missing.png"
    validates_attachment_content_type :avatar2, content_type: /\Aimage\/.*\Z/
end

app/controllers/about_us_controller.rb
class AboutUsController < ApplicationController
  before_action :set_about_u, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /about_us
  # GET /about_us.json
  def index
    @about_us = AboutU.all
  end

  # GET /about_us/1
  # GET /about_us/1.json
  def show
  end

  # GET /about_us/new
  def new
    @about_u = AboutU.new
  end

  # GET /about_us/1/edit
  def edit
  end

  # POST /about_us
  # POST /about_us.json
  def create
    @about_u = AboutU.new(about_u_params)

    respond_to do |format|
      if @about_u.save
        format.html { redirect_to @about_u, notice: 'About u was successfully created.' }
        format.json { render :show, status: :created, location: @about_u }
      else
        format.html { render :new }
        format.json { render json: @about_u.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /about_us/1
  # PATCH/PUT /about_us/1.json
  def update
    respond_to do |format|
      if @about_u.update(about_u_params)
        format.html { redirect_to @about_u, notice: 'About u was successfully updated.' }
        format.json { render :show, status: :ok, location: @about_u }
      else
        format.html { render :edit }
        format.json { render json: @about_u.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /about_us/1
  # DELETE /about_us/1.json
  def destroy
    @about_u.destroy
    respond_to do |format|
      format.html { redirect_to about_us_url, notice: 'About u was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_about_u
      @about_u = AboutU.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def about_u_params
      params.require(:about_u).permit(:first_title, :second_title, :third_title, :first_description, :second_description, :third_description, :avatar, :avatar1, :avatar2)
    end
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/views/about_us/_about_us1.html.erb
<section class="container-fluid about white-color no-padding" id="about">
    <% @about_us.each do |about_us| %>
    <div class="about-background about-background-1 row no-margin">
        <div class="col-md-6 about-black-box">
        	<h3 class="section-heading"><%=about_us.first_title%></h3>
        	<p><%=about_us.first_description%>.</p>
        	<a href="#about_us1" class="btn btn-default">¿Por qué nosotros?</a>
        </div>
        <div class="col-md-6"></div>
    </div>

    <div class="about-background about-background-2 row no-margin" id="about_us1">
        <div class="col-md-4 about-white-box col-md-offset-4">
	        <h2 class="section-claim wow fadeInDown" data-wow-delay="0.2s" style="visibility: visible; animation-delay: 0.2s; animation-name: fadeInDown;">
	        <%=about_us.second_title%>
	        	
	        </h2>
        	
        	<p><p><%=about_us.second_description%>.</p>.</p>

        	<a href="#about_us2" class="btn btn-default">¿con qué visión?</a>
        </div>
        <div class="col-md-4"></div>
    </div>

    <div class="about-background about-background-3 row no-margin" id="about_us2">
        <div class="col-md-6 about-black-box col-md-offset-6">
        	<h3 class="section-heading"><%=about_us.third_title%></h3>
            <p><%=about_us.third_description%>.</p>
        	

        	<a href="#contact" class="btn btn-default">contactanos</a>
        </div>
    </div>
    <%end%>
  </section>

app/views/about_us/_form.html.erb
<%= form_with(model: about_u, local: true) do |form| %>
  <% if about_u.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(about_u.errors.count, "error") %> prohibited this about_u from being saved:</h2>

      <ul>
      <% about_u.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_title %>
    <%= form.text_field :first_title, id: :about_u_first_title, :class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :second_title %>
    <%= form.text_field :second_title, id: :about_u_second_title, :class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :third_title %>
    <%= form.text_field :third_title, id: :about_u_third_title, :class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :first_description %>
    <%= form.text_area :first_description, id: :about_u_first_description, :class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :second_description %>
    <%= form.text_area :second_description, id: :about_u_second_description, :class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :third_description %>
    <%= form.text_area :third_description, id: :about_u_third_description, :class => "form-control" %>
  </div>

  <div class="field">
        <%= form.label :"imagen1" %><br />
        <%= form.file_field :avatar %>
    </div>

     <div class="field">
        <%= form.label :"imagen2" %><br />
        <%= form.file_field :avatar1 %>
    </div>

     <div class="field">
        <%= form.label :"imagen3" %><br />
        <%= form.file_field :avatar2 %>
    </div>

  <div class="actions">
    <%= form.submit :type => "submit", :class => "btn btn-default" %>
  </div>
<% end %>

app/views/about_us/edit.html.erb
<h1>Editing About U</h1>

<%= render 'form', about_u: @about_u %>

<%= link_to 'Show', @about_u %> |
<%= link_to 'Back', about_us_path %>

app/views/about_us/index.html.erb
<p id="notice"><%= notice %></p>

<h1>About Us</h1>

<table>
  <thead>
    <tr>
      <th>First title</th>
      <th>Second title</th>
      <th>Third title</th>
      <th>First description</th>
      <th>Second description</th>
      <th>Third description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @about_us.each do |about_u| %>
      <tr>
        <td><%= about_u.first_title %></td>
        <td><%= about_u.second_title %></td>
        <td><%= about_u.third_title %></td>
        <td><%= about_u.first_description %></td>
        <td><%= about_u.second_description %></td>
        <td><%= about_u.third_description %></td>
        <td><%= link_to 'Show', about_u %></td>
        <td><%= link_to 'Edit', edit_about_u_path(about_u) %></td>
        <td><%= link_to 'Destroy', about_u, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New About U', new_about_u_path %>

app/views/about_us/new.html.erb
<div class="col-md-8 col-md-push-1">
<h1 class="section-heading white-color">Nuevo Nosotros</h1>

<%= render 'form', about_u: @about_u %>

<%= link_to 'Back', about_us_path %>

app/views/about_us/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First title:</strong>
  <%= @about_u.first_title %>
</p>

<p>
  <strong>Second title:</strong>
  <%= @about_u.second_title %>
</p>

<p>
  <strong>Third title:</strong>
  <%= @about_u.third_title %>
</p>

<p>
  <strong>First description:</strong>
  <%= @about_u.first_description %>
</p>

<p>
  <strong>Second description:</strong>
  <%= @about_u.second_description %>
</p>

<p>
  <strong>Third description:</strong>
  <%= @about_u.third_description %>
</p>

<%= link_to 'Edit', edit_about_u_path(@about_u) %> |
<%= link_to 'Back', about_us_path %>