config/routes.rb
Rails.application.routes.draw do
  resources :workshops
  resources :about_us
  resources :courses
  resources :homes
  root to: 'welcome#index'

  devise_scope :user do
  	get "/sign_up" => "devise/registrations#new", :as => "iglawebregistro" #custom path
  end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/home.rb
class Home < ApplicationRecord
	has_attached_file :avatar, styles: { medium: "300x300", thumb:"100x100"}, default_url: "missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.require(:home).permit(:tittle, :avatar)
    end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_form.html.erb
<%= form_with(model: home, local: true) do |form| %>
  <% if home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :titulo %>
    <%= form.text_field :tittle, id: :home_tittle, :class => "form-control" %>
  </div>

   <div class="form-group">
        <%= form.label :"imagen" %><br />
        <%= form.file_field :avatar %>
    </div>
  <div class="actions">
    <%= form.submit :type => "submit", :class => "btn btn-default" %>
  </div>
<% end %>

app/views/homes/_home1.html.erb
<section class="home section image-slider" id="home">
		<div class="home-slider text-center">
			
			<div class="swiper-wrapper">
				<% @homes.each do |home| %>
				<div class="swiper-slide" style="background: url(<%=home.avatar.url()%>);">
					
					<h2 class="home-slider-title-main black-color"><%= home.tittle %></h2>
					<div class="home-buttons text-center"> <a href="#courses" class="btn btn-lg  btn-primary">Cursos</a> </div>
					<a class="arrow bounce text-center" href="#courses"> <span class="ti-mouse"></span> <span class="ti-angle-double-down"></span> </a>
				</div>

				
				
				<%end%>
			</div>
			
			<div class="home-pagination"></div>
			<div class="home-slider-next right-arrow-negative"> <span class="ti-arrow-right"></span> </div>
			<div class="home-slider-prev left-arrow-negative"> <span class="ti-arrow-left"></span> </div>
		</div>
	</section>

app/views/homes/edit.html.erb
<h1>Editing Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Homes</h1>

<table>
  <thead>
    <tr>
      <th>Tittle</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @homes.each do |home| %>
      <tr>
        <td><%= home.tittle %></td>
        <td><%= link_to 'Show', home %></td>
        <td><%= link_to 'Edit', edit_home_path(home) %></td>
        <td><%= link_to 'Destroy', home, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Home', new_home_path %>

app/views/homes/new.html.erb
<div class="col-md-8 col-md-push-1">
<h1 class="section-heading white-color">Nuevo Slider</h1>

<%= render 'form', home: @home %>

<%= link_to 'Back', homes_path %>
</div>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tittle:</strong>
  <%= @home.tittle %>
</p>

<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>